# Generated by Django 3.2.6 on 2021-09-26 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_comment_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='posted_comments',
            new_name='post',
        ),
    ]
